# Use the Netlify UI for private/secret environment variables.
# Don't use this file for that!
# This file needs to be committed to GitHub.

[build]
  publish = "public"
  command = "npm run build"
  
[build.environment]
  YARN_VERSION = "1.5.1"
  YARN_FLAGS = "--no-ignore-optional"

[context.production.environment]
  GATSBY_SHOW_DOCS = "false"

[context.deploy-preview.environment]
  GATSBY_SHOW_DOCS = "false"

[context.branch-deploy.environment]
  GATSBY_SHOW_DOCS = "true"
  GATSBY_ALGOLIA_INDEX_NAME = "test_overturedocs"
  GATSBY_ALGOLIA_APP_ID = "6R0DWJUJIU"
  GATSBY_ALGOLIA_SEARCH_KEY = "bbea2e1901e572afa623f7edaece8861"
